export enum RedirectStatusCode {
	MULTIPLE_CHOICES = 300,
	MOVED_PERMANENTLY,
	FOUND,
	SEE_OTHER,
	NOT_MODIFIED,
	USE_PROXY,
	UNUSED,
	TEMPORARY_REDIRECT,
	PERMANENT_REDIRECT
}

export enum ClientStatusCode {
	BAD_REQUEST = 400
}
