// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'hu'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * O​r​d​e​r​s
		 */
		orders: string
		/**
		 * C​u​s​t​o​m​e​r​s
		 */
		customers: string
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Orders
		 */
		orders: () => LocalizedString
		/**
		 * Customers
		 */
		customers: () => LocalizedString
	}
}

export type Formatters = {}
